# Generated by Django 4.2.1 on 2023-06-07 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_event_date_remove_event_time_event_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='timestamp',
            new_name='event_date_time',
        ),
    ]
