# Generated by Django 4.2.1 on 2023-06-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
